package com.cafeapp.views;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pranav Sharma LMU ID:23048577
 */
public class LoadingForm extends javax.swing.JFrame {

    /**
     * Creates new form LoadingForm
     */
    public LoadingForm() {
        initComponents();
        Thread loadingPercentage = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {
                    Loadingbar.setValue(i);
                    try {
                        Thread.sleep(20);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LoadingForm.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    if (Loadingbar.getString().equals("10%")) {
                        lblLoadingTitle.setText("Starting up ");
                    } else if (Loadingbar.getString().equals("25%")) {
                        lblLoadingTitle.setText("Loading resources...");
                    } else if (Loadingbar.getString().equals("50%")) {
                        lblLoadingTitle.setText("Initializing components...");
                    } else if (Loadingbar.getString().equals("75%")) {
                        lblLoadingTitle.setText("Finalizing setup...");
                    } else if (Loadingbar.getString().equals("100%")) {
                        lblLoadingTitle.setText("Application loaded successfully!");
                        new Login().setVisible(true);
                        LoadingForm.this.dispose();
                        //                            System.exit(0);
                    }
                }

            }
        });
        loadingPercentage.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Loadingbar = new javax.swing.JProgressBar();
        lblLoadingTitle = new javax.swing.JLabel();
        lblforbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loadingbar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Loadingbar.setStringPainted(true);
        getContentPane().add(Loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1366, 50));

        lblLoadingTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        getContentPane().add(lblLoadingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 660, 290, 50));

        lblforbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loadingbackgroundforhome.jpg"))); // NOI18N
        getContentPane().add(lblforbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1980, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Loadingbar;
    private javax.swing.JLabel lblLoadingTitle;
    private javax.swing.JLabel lblforbackground;
    // End of variables declaration//GEN-END:variables
}
