package com.cafeapp.views;

import javax.swing.JOptionPane;

/**
 *
 * @author Pranav Sharma LMU ID:23048577
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtfldusername = new javax.swing.JTextField();
        txtfldpassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        lblforgotpassword = new javax.swing.JLabel();
        lblloginimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 57)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(204, 153, 0));
        lblLogin.setText("User Login");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblusername.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        lblusername.setText("Username");
        getContentPane().add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        txtfldusername.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        getContentPane().add(txtfldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 351, -1));

        txtfldpassword.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        getContentPane().add(txtfldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 351, -1));

        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 130, -1));

        btnSignup.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        btnSignup.setText("Signup");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        lblforgotpassword.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblforgotpassword.setForeground(new java.awt.Color(255, 255, 255));
        lblforgotpassword.setText("Forgot Password?");
        getContentPane().add(lblforgotpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 433, -1, -1));

        lblloginimg.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblloginimg.setForeground(new java.awt.Color(255, 255, 255));
        lblloginimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logintheme.jpg"))); // NOI18N
        getContentPane().add(lblloginimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 // This method is used to go to signup page when Signup Button is clicked
    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed

        setVisible(false);
        new Signup().setVisible(true);

    }//GEN-LAST:event_btnSignupActionPerformed
    // This method is used to go to Hone page when Login button is pressed
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try{
            if(txtfldusername.getText().isEmpty()&& txtfldpassword.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please fill in all the fields given in the form", "Empty Fields", JOptionPane.WARNING_MESSAGE);
            }
            else if(txtfldusername.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please fill in the username in the form", "Empty Username Field", JOptionPane.WARNING_MESSAGE);
            }else if(txtfldpassword.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please fill in the password in the form", "Empty Password Field", JOptionPane.WARNING_MESSAGE);
            }else{
                setVisible(false);
                new Home().setVisible(true);
                
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Details", "Invalid", JOptionPane.ERROR_MESSAGE);
            
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblforgotpassword;
    private javax.swing.JLabel lblloginimg;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPasswordField txtfldpassword;
    private javax.swing.JTextField txtfldusername;
    // End of variables declaration//GEN-END:variables
}
